#!/bin/sh

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
case $REBOOT in "");;*)
	# Otherwise sb_watchdog() does not work
	/etc/init.d/S40network start
	exec reboot
;;esac

for i in /etc/init.d/S??* ;do

	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue

	case "$i" in
	*.sh)
		# Source shell script for speed.
		(
			trap - INT QUIT TSTP
			set start
			. $i
		)
	;;
	*)
		# No sh extension, so fork subprocess.
		$i start
	;;
	esac
done
