#!/bin/sh

case $FAILSAFE in "");;*)exit;;esac

case $1 in
	start)
		echo "Starting olsr prio..."
		for DEV in $(sed -ne'/^Interface/{s/^Interface//;s/"//g;p}' /etc/olsrd.conf);do
			test -z "${DEV#ath[0-9]}" && DEV=wifi0
			tc qdisc add dev $DEV root handle 1: prio
			tc qdisc add dev $DEV parent 1:1 handle 10: sfq perturb 10
			tc qdisc add dev $DEV parent 1:2 handle 20: sfq perturb 10
			tc qdisc add dev $DEV parent 1:3 handle 30: sfq perturb 10
			tc filter add dev $DEV protocol ip parent 1: prio 1 u32 match ip protocol 17 0xff match ip dport 698 0xffff flowid 1:1
			tc filter add dev $DEV protocol ip parent 1: prio 2 u32 match ip protocol 6 0xff match u8 0x10 0xff at nexthdr+13 flowid 1:1
			tc filter add dev $DEV protocol ip parent 1: prio 3 u32 match ip protocol 17 0xff match ip dport 53 0xffff flowid 1:2
			tc filter add dev $DEV protocol ip parent 1: prio 4 u32 match u16 0x00ff 0xff00 at 2 flowid 1:2
			tc filter add dev $DEV protocol ip parent 1: prio 5 u32 match ip protocol 0 0x00 flowid 1:3
		done
	;;
	stop)
		echo "Stopping olsr prio..."
		for DEV in $(sed -ne'/^Interface/{s/^Interface//;s/"//g;p}' /etc/olsrd.conf);do
			test -z "${DEV#ath[0-9]}" && DEV=wifi0
			tc filter del dev $DEV protocol ip parent 1: prio 5 u32 match ip protocol 0 0x00 flowid 1:3
			tc filter del dev $DEV protocol ip parent 1: prio 4 u32 match u16 0x00ff 0xff00 at 2 flowid 1:2
			tc filter del dev $DEV protocol ip parent 1: prio 3 u32 match ip protocol 17 0xff match ip dport 53 0xffff flowid 1:2
			tc filter del dev $DEV protocol ip parent 1: prio 2 u32 match ip protocol 6 0xff match u8 0x10 0xff at nexthdr+13 flowid 1:1
			tc filter del dev $DEV protocol ip parent 1: prio 1 u32 match ip protocol 17 0xff match ip dport 698 0xffff flowid 1:1
			tc qdisc del dev $DEV parent 1:3 handle 30: sfq perturb 10
			tc qdisc del dev $DEV parent 1:2 handle 20: sfq perturb 10
			tc qdisc del dev $DEV parent 1:1 handle 10: sfq perturb 10
			tc qdisc del dev $DEV root handle 1: prio
		done
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 start|stop|restart"
	;;
esac
