#!/bin/sh

wget -q -O /tmp/index-$$.html http://localhost:2006/
for ip in $(sed -n '/^Table: HNA/,/^$/s/^0.0.0.0\/0[[:space:]]\+//p' /tmp/index-$$.html|sort);do
	sed -ne'/^Table: Routes/,${s#/32##;p}' /tmp/index-$$.html|grep "^$ip	"
done
rm -f /tmp/index-$$.html
